### ISSUE TITLE
images sizing

### ISSUE THREAD

**Issue by wisdommichaels** [wisdommichaels/Store-Landing-Page#1]
**the  images on this projects are not having the same sizing pls how will that be resolved?** 
 YOU CAN VIEW IT FROM THE LINK BELLOW.
https://wisdommichaels.github.io/Store-Landing-Page/

**Comment by o-david** [comment]
I have resolved the issue, please review and close the issue

**Comment by wisdommichaels** [comment]
thank you so much sir..
