### ISSUE TITLE
Make the Site Responsive

### ISSUE THREAD

**Issue by o-david** [wisdommichaels/Store-Landing-Page#2]
## Issue: Make the Site Responsive

**Description:**

The current site layout does not adapt well to different screen sizes, resulting in poor user experience on mobile devices and tablets. To ensure the site is accessible and user-friendly across all devices, we need to implement responsive design practices.

**Steps to Reproduce:**
1. Open the site on a desktop browser.
2. Resize the browser window to different widths (e.g., mobile, tablet, desktop).
3. Observe the layout and content adjustments.

**Expected Behavior:**
The site should adjust its layout and content to fit different screen sizes seamlessly. Elements should resize and reposition themselves appropriately to maintain usability and readability.

**Actual Behavior:**
The site does not adjust well to different screen sizes, resulting in overlapping elements, unreadable text, and poor overall layout on smaller screens.

**Proposed Solution:**
1. **Implement Media Queries:**
   Use CSS media queries to apply different styles based on screen size.
   ```css
   @media (max-width: 768px) {
       /* Styles for tablets */
   }

   @media (max-width: 480px) {
       /* Styles for mobile phones */
   }
   ```

2. **Flexible Grid System:**
   Use a flexible grid system (e.g., CSS Grid or Flexbox) to create a responsive layout.
   ```css
   .container {
       display: flex;
       flex-wrap: wrap;
   }

   .item {
       flex: 1 1 100%; /* Adjust the basis for different screen sizes */
   }
   ```

**Additional Context:**
Improving the site's responsiveness will enhance the user experience, making it more accessible and usable on a wider range of devices, from desktops to smartphones.

**Comment by wisdommichaels** [comment]
thank you sir the said issue has been resolved
